-- =============================================================================
-- Migration 0017 – Sprint 15: AI Product Discovery – product_candidates
-- =============================================================================
-- Stores scored product candidates generated by the discovery pipeline.
-- One row per (canonical_product_id) per daily discovery run.
-- The pipeline keeps the top-50 candidates and rejects or marks the rest.
-- =============================================================================

CREATE TABLE IF NOT EXISTS product_candidates (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- FK → canonical_products.id (not ENFORCED at DB level for portability)
    canonical_product_id UUID       NOT NULL,

    -- Source trend signal (optional – NULL if candidate was injected manually)
    trend_product_id    UUID,           -- FK → trend_products.id (soft)

    -- ── Score components (0.0 – 1.0 each) ───────────────────────────────────
    trend_score         NUMERIC(8,4) NOT NULL DEFAULT 0,  -- from trend signal
    margin_score        NUMERIC(8,4) NOT NULL DEFAULT 0,  -- derived from last_price vs cost
    competition_score   NUMERIC(8,4) NOT NULL DEFAULT 0,  -- inverse of competitor count / price gap
    supplier_score      NUMERIC(8,4) NOT NULL DEFAULT 0,  -- IN_STOCK supplier availability
    content_score       NUMERIC(8,4) NOT NULL DEFAULT 0,  -- name/brand/image completeness

    -- ── Weighted composite score ─────────────────────────────────────────────
    -- final = trend*0.35 + margin*0.25 + competition*0.20 + supplier*0.10 + content*0.10
    final_score         NUMERIC(8,4) NOT NULL DEFAULT 0,

    -- ── Lifecycle ────────────────────────────────────────────────────────────
    -- candidate  → ready for human review / auto-publish
    -- published  → sent to Shopify via publish_service
    -- rejected   → discarded (too low score, out-of-stock, etc.)
    status              VARCHAR(32)  NOT NULL DEFAULT 'candidate',

    notes               TEXT,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One candidate per canonical product (latest run overwrites / coexists by date)
-- Allow multiple runs: no unique on canonical alone; uniqueness enforced in service.
CREATE INDEX IF NOT EXISTS idx_product_candidates_canonical_product_id
    ON product_candidates (canonical_product_id);

CREATE INDEX IF NOT EXISTS idx_product_candidates_final_score_desc
    ON product_candidates (final_score DESC);

CREATE INDEX IF NOT EXISTS idx_product_candidates_status
    ON product_candidates (status);

CREATE INDEX IF NOT EXISTS idx_product_candidates_created_at_desc
    ON product_candidates (created_at DESC);
