from __future__ import annotations

"""
app/models/product_candidate.py
─────────────────────────────────
Sprint 15 – ORM model for scored product candidates from the discovery pipeline.

Table: product_candidates
One discovery run produces up to 50 candidate rows.  Each row links a canonical
product to a scoring breakdown so the business can review and publish the best
opportunities.

Status lifecycle
----------------
candidate  →  published   (admin pressed "Publish" or scheduled auto-publish)
           →  rejected    (score too low, manually dismissed, or out-of-stock)

Score formula
-------------
final_score = trend_score * 0.35
            + margin_score * 0.25
            + competition_score * 0.20
            + supplier_score * 0.10
            + content_score * 0.10
"""

import uuid

from sqlalchemy import Column, DateTime, Numeric, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    pass


# ── Status constants ──────────────────────────────────────────────────────────

class CandidateStatus:
    CANDIDATE = "candidate"
    PUBLISHED = "published"
    REJECTED  = "rejected"


# ── ORM Model ─────────────────────────────────────────────────────────────────

class ProductCandidate(Base):
    """
    Scored product candidate generated by the Sprint 15 discovery pipeline.

    Columns
    -------
    id                   : UUID primary key
    canonical_product_id : FK → canonical_products.id (soft reference)
    trend_product_id     : FK → trend_products.id (soft, nullable)
    trend_score          : 0.0 – 1.0 normalised (from trend signal, divided by 10)
    margin_score         : 0.0 – 1.0 derived from margin headroom
    competition_score    : 0.0 – 1.0 inverse of competitor density / price gap
    supplier_score       : 0.0 – 1.0 IN_STOCK supplier availability ratio
    content_score        : 0.0 – 1.0 product data completeness
    final_score          : Weighted composite (see formula above)
    status               : candidate | published | rejected
    notes                : Free-text notes / rejection reason
    created_at / updated_at : Audit timestamps
    """

    __tablename__ = "product_candidates"
    __allow_unmapped__ = True

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Soft FK – not enforced at DB level to allow flexible SQLite testing
    canonical_product_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    trend_product_id     = Column(UUID(as_uuid=True), nullable=True)

    # ── Score components (0.0 – 1.0) ─────────────────────────────────────────
    trend_score       = Column(Numeric(8, 4), nullable=False, default=0)
    margin_score      = Column(Numeric(8, 4), nullable=False, default=0)
    competition_score = Column(Numeric(8, 4), nullable=False, default=0)
    supplier_score    = Column(Numeric(8, 4), nullable=False, default=0)
    content_score     = Column(Numeric(8, 4), nullable=False, default=0)

    # ── Weighted composite ────────────────────────────────────────────────────
    final_score = Column(Numeric(8, 4), nullable=False, default=0)

    # ── Lifecycle ─────────────────────────────────────────────────────────────
    status = Column(String(32), nullable=False, default=CandidateStatus.CANDIDATE)
    notes  = Column(Text, nullable=True)

    # ── Audit ─────────────────────────────────────────────────────────────────
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    def __repr__(self) -> str:
        return (
            f"<ProductCandidate id={self.id} "
            f"canonical_product_id={self.canonical_product_id} "
            f"final_score={self.final_score} status={self.status!r}>"
        )
